version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://abc123:abc123@postgres:5432/bookstoredb
      NODE_ENV: development
      PORT: 3000
    ports:
      - "5000:3000"

  postgres:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: abc123
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: bookstoredb
